"""Remove username from User table

Revision ID: 29584fb73c9c
Revises: 2738a3ac169a
Create Date: 2025-01-23 22:22:25.826348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29584fb73c9c'
down_revision = '2738a3ac169a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
